# vim: set relativenumber nonu shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
version: "3.8"

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.4
    networks:
      - graylog
    volumes:
      - mongodb:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

# Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    networks:
      - graylog
    volumes:
      - es-db:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 1g
          cpus: '2.0'
  # Graylog: https://hub.docker.com/r/graylog/graylog/

  graylog:
    image: graylog/graylog:3.3.5
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://10.20.20.141:9041/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    networks:
      - graylog
    volumes:
      - graylogdata:/usr/share/graylog/data
      - geocity:/etc/graylog/server/
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9041:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes:
  mongodb:
    driver_opts:
      o: bind
      type: none
      device: /data/graylog/mongodb
  graylogdata:
    driver_opts:
      o: bind
      type: none
      device: /data/graylog/graylogdata
  es-db:
    driver_opts:
      o: bind
      type: none
      device: /data/graylog/elasticsearch
  geocity:
    driver_opts:
      o: bind
      type: none
      device: /data/graylog/geocity

networks:
  graylog:
    driver: overlay
