#·vim:·set·relativenumber·nonu·shiftwidth=2·tabstop=2·softtabstop=-1·expandtab:
version: "3.8"

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
    networks:
      - graylog
    volumes:
      - mongodb:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

# Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.0
    networks:
      - graylog
    volumes:
      - es-db:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 1g
  elasticsearch02:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.0
    environment:
      - node.name=es02
      - http.host=0.0.0.0
      - discovery.seed_hosts=es01,es03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  elasticsearch03:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.0
    environment:
      - node.name=es03
      - http.host=0.0.0.0
      - transport.host=localhost
      - discovery.seed_hosts=es02,es01
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=es-docker-cluster
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  # Graylog: https://hub.docker.com/r/graylog/graylog/

  graylog:
    image: graylog/graylog:3.3
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    networks:
      - graylog
    volumes:
      - greylogdata:/usr/share/graylog/data
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes:
  mongodb:
    driver_opts:
      o: bind
      type: none
      device: /data/greylog/mongodb
  greylogdata:
    driver_opts:
      o: bind
      type: none
      device: /data/greylog/graylogdata

networks:
  graylog:
    driver: overlay
